### ISSUE TITLE
Trigger file refresh (in browse) after copy

### ISSUE THREAD

**Issue by lordspace** [orbisius/orbisius-child-theme-creator#1]
After files are copied there receiving theme should have its file window refreshed.
![image](https://user-images.githubusercontent.com/137558/94699716-4cbbcb80-0343-11eb-8b06-d59adf1b248e.png)

the dropdown should also be refreshed
![image](https://user-images.githubusercontent.com/137558/94699987-a0c6b000-0343-11eb-9178-e857af33ea9d.png)

**Comment by chozze** [comment]
Resolved in latest ales-branch
